version: "2"
services:
  node:
    image: "pitshifer/remi"
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/usr/src/app
      - ./logs/:/var/log/remi
    working_dir: /usr/src/app
    expose:
      - "80"
    links:
      - mongodb
    command: ["nodemon", "index.js"]

  mongodb:
    image: "mongo"
    volumes:
      - ./data/db:/data/db
